[project]
name = "http-spray"
version = "0.0.11"
description = ""
authors = [{name = "dadevel",email = "dadevel@disroot.org"}]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests-ntlm>=1.3.0",
    "requests[socks]>=2.34.0",
]

[project.scripts]
http-spray = "httpspray.main:main"
